### ISSUE TITLE
The MyOrder component should be renamed to OrderHistory

### ISSUE THREAD

**Issue by stevebrownlee** [nss-day-cohort-33/bangazon-public-api-galydia-empire#57]
This component lists all orders for the customer, so the name of the component should match its responsibility.

https://github.com/nss-day-cohort-33/bangazon-client-application-galydia-empire/blob/master/src/components/order/MyOrder.js

**Comment by MCaldwell-42** [comment]
Done on Joy's current branch.  Will recheck before he pushes up
